<a href="https://colab.research.google.com/github/visheshagrawal/Conditional-Novel-Recipe-Generation/blob/main/NovRecGen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import pandas as pd
import random
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
import math

#Preprocessing of Recipe NDB

In [ ]:
import pandas as pd
df_small = pd.read_csv("/content/drive/MyDrive/COSY/Recipe_small.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (2,3,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
df_small.head()

   Recipe_id  Calories  ... lacto_vegetarian ovo_lacto_vegetarian
0       2610     196.0  ...              0.0                  0.0
1       2611      80.0  ...              0.0                  0.0
2       2612     339.0  ...              0.0                  0.0
3       2613     409.0  ...              1.0                  0.0
4       2614      45.0  ...              0.0                  0.0

[5 rows x 24 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/COSY/Recipe_correct_ndb.csv")
df.head()

   recipe_no          ingredient_Phrase  ingredient  ... ing_id ndb_id M_or_A
0       2610               3 cups water       water  ...      3  14555      M
1       2610          1 cup red lentils  red lentil  ...    452  16144      A
2       2610  1 roma tomato , quartered  rom tomato  ...    180  93600      A
3       2610       1 carrot , quartered      carrot  ...     21  11124      M
4       2610  1 small onion , quartered       onion  ...      1  11282      M

[5 rows x 12 columns]

In [ ]:
recipe_ids=list(set(df["recipe_no"].to_list()))
# for i in range()

In [ ]:
df.columns

Index(['recipe_no', 'ingredient_Phrase', 'ingredient', 'state', 'quantity',
       'unit', 'temp', 'df', 'size', 'ing_id', 'ndb_id', 'M_or_A'],
      dtype='object')

In [ ]:
recipe_ingredient_dict = {}
for i in recipe_ids:
  if i%100 == 0:
    print(i)
  new_df = df[df["recipe_no"]==i]
  recipe_ingredient_dict[i] = new_df["ingredient"].to_list()

In [ ]:
recipe_df = pd.DataFrame()
recipe_df["recipe_no"] = recipe_ingredient_dict.keys()
recipe_df["ingredients"] = recipe_ingredient_dict.values()
recipe_df["size"] = recipe_df["ingredients"].apply(lambda x: len(x))
recipe_df.head()

   recipe_no                                        ingredients  size
0       2610  [water, red lentil, rom tomato, carrot, onion,...    11
1       2611  [vegetable oil, onion, tomato paste, garlic, c...     9
2       2612  [olive oil, onion, lamb shoulder, salt black p...     7
3       2613  [onion, olive oil, garbanzo bean, cream, cornm...    12
4       2614  [hazelnut, sesame seed, coriander seed, cumin ...     6

In [ ]:
recipe_df = recipe_df.rename(columns={"recipe_no":"Recipe_id"})
recipe_df.head()

   Recipe_id                                        ingredients  size
0       2610  [water, red lentil, rom tomato, carrot, onion,...    11
1       2611  [vegetable oil, onion, tomato paste, garlic, c...     9
2       2612  [olive oil, onion, lamb shoulder, salt black p...     7
3       2613  [onion, olive oil, garbanzo bean, cream, cornm...    12
4       2614  [hazelnut, sesame seed, coriander seed, cumin ...     6

#Merging the 2 dataframes

In [ ]:
#Merge the 2 datasets
combined_df = pd.merge(recipe_df,df_small,on="Recipe_id")

In [ ]:
combined_df.to_csv("/content/drive/MyDrive/COSY/combined_df.csv")

In [ ]:
# test= pd.read_csv("/content/drive/MyDrive/Academic/COSY/combined_df.csv")
# test

In [ ]:
combined_df

        Recipe_id  ... ovo_lacto_vegetarian
0            2610  ...                  0.0
1            2611  ...                  0.0
2            2612  ...                  0.0
3            2613  ...                  0.0
4            2614  ...                  0.0
...           ...  ...                  ...
118107     149187  ...                  0.0
118108     149188  ...                  0.0
118109     149189  ...                  0.0
118110     149190  ...                  0.0
118111     149191  ...                  0.0

[118112 rows x 26 columns]

In [ ]:
combined_df.groupby(['Sub_region']).mean()["size"]

Sub_region
Angolan         7.166667
Argentine      10.886593
Australian      8.795818
Austrian       10.017647
Bangladeshi    14.625000
                 ...
UK              9.732323
US              9.557941
Venezuelan      9.259259
Vietnamese     12.361582
Welsh           8.976526
Name: size, Length: 75, dtype: float64

#Using probability finding ingredients based on popularity

Based on Popularity find probabilities and then using avg size of cuisine select those many number of ingredients.

In [ ]:
combined_df= pd.read_csv("/content/drive/MyDrive/Academic/COSY/combined_df.csv")
# combined_df= pd.read_csv("/content/drive/MyDrive/COSY/combined_df.csv")

In [ ]:
# result_combined = []
# for cuisine in set(combined_df["Sub_region"]):
#   temp_df = combined_df[combined_df["Sub_region"]==cuisine]
#   result = []
#   for ind in temp_df.index:
#     result.extend(temp_df["ingredients"][ind])
#   result_combined.append(result)

In [ ]:
# # result_combined
# count_result_combined = []
# from collections import Counter
# for result in result_combined:
#   counter_result = Counter(result).most_common()
#   count_result_combined.append(counter_result)
# len(count_result_combined)

75

In [ ]:
# percentage_share_ingredients_combined = []
# for counter_result in count_result_combined:
#   percentage_share_ingredients = []
#   for i,j in counter_result:
#     percentage_share_ingredients.append((i,j/len(counter_result)))
#   percentage_share_ingredients_combined.append(percentage_share_ingredients)
# percentage_share_ingredients_combined

In [ ]:
# first_tuple_elements = [a_tuple[0] for a_tuple in count_result_combined[0]]
# second_tuple_elements = [a_tuple[1] for a_tuple in count_result_combined[0]]
# # second_tuple_elements

In [ ]:
# combined_df.groupby(['Sub_region']).mean()

In [ ]:
# import random
# set_random_ingredient = set()
# while len(set_random_ingredient) < 10:
#   set_random_ingredient.add(random.choices(first_tuple_elements, weights=second_tuple_elements)[0])
# set_random_ingredient

{' ', ',', 'e', 'l', 'm', 'n', 'r', 's', 't', 'u'}

In [ ]:
# combined_df= pd.read_csv("/content/drive/MyDrive/Academic/COSY/combined_df.csv")
# # combined_df= pd.read_csv("/content/drive/MyDrive/COSY/combined_df.csv")

In [ ]:
combined_df

,Unnamed: 0,Recipe_id,ingredients,size,Calories,cook_time,prep_time,servings,Recipe_title,total_time,...,Energy (kcal),Protein (g),Total lipid (fat) (g),Utensils,Processes,vegan,pescetarian,ovo_vegetarian,lacto_vegetarian,ovo_lacto_vegetarian
0,0,2610,"['water', 'red lentil', 'rom tomato', 'carrot'...",11,196.0,30,15,4,Egyptian Lentil Soup,45,...,805.6975,49.5540,5.6564,NaN,place||heat||cook||remove||cool||blend||smooth...,0.0,0.0,0.0,0.0,0.0
1,1,2611,"['vegetable oil', 'onion', 'tomato paste', 'ga...",9,80.0,35,10,4,Egyptian Green Beans with Carrots,45,...,386.7670,15.5638,19.7239,pot,heat||heat||cook||stir||stir||cook||stirring||...,0.0,0.0,0.0,0.0,0.0
2,2,2612,"['olive oil', 'onion', 'lamb shoulder', 'salt ...",7,339.0,120,15,4,Egyptian Bamia,135,...,1762.7662,82.9034,146.8971,saucepan||oven||dish||oven,heat||heat||cook||stir||mix||cook||stir||stir|...,0.0,0.0,0.0,0.0,0.0
3,3,2613,"['onion', 'olive oil', 'garbanzo bean', 'cream...",12,409.0,15,15,3,Magpie's Easy Falafel Cakes,60,...,1686.8298,67.8589,62.4829,skillet||processor||bowl||cup||dish||tablespoo...,cook||smooth||transfer||stir||cover||chill||pl...,0.0,0.0,0.0,1.0,0.0
4,4,2614,"['hazelnut', 'sesame seed', 'coriander seed', ...",6,45.0,5,20,24,Dukkah,25,...,1006.2380,26.1800,73.1713,oven||sheet||skillet||bowl||skillet||pan||proc...,preheat||place||pour||fold||cover||remove||coo...,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118107,118107,149187,"['jerusalem artichoke', 'jalapeno pepper', 're...",10,90.4,0,0,2,Jerusalem Artichoke Stir Fry,23,...,40.2812,1.7664,0.3396,skillet,spray||cook||cook||add||stir||serve,0.0,0.0,0.0,0.0,0.0
118108,118108,149188,"['asian pear', 'water', 'ginger', 'cardamom se...",4,1.0,0,0,6-8,Asian Apple Pear Compote,35,...,1.6000,0.0364,0.0150,saucepan,place||cook||heat||add||remove||serve,0.0,0.0,0.0,0.0,0.0
118109,118109,149189,"['olive oil', 'onion', 'potato', 'vegetable st...",6,122.4,0,0,3,Skillet Sweet Potatoes,35,...,149.0850,2.0252,9.2374,skillet||skillet,heat||cook||stirring||add||cover||simmer||stir...,1.0,1.0,0.0,0.0,0.0
118110,118110,149190,"['margarine', 'sugar', 'vanilla', 'baking powd...",7,83.0,0,0,18 cookies,Any-Flavour Cookies,33,...,1954.0830,17.6848,91.6479,oven||sheet||fork,cream||mix||dry||add||preheat||bake,1.0,1.0,0.0,0.0,0.0
118111,118111,149191,"['raisin', 'fig', 'water', 'date', 'butter', '...",8,274.4,0,0,9 bars,"Fig Newton "" Sarah - Bars """,15,...,3975.5505,72.5065,133.0444,bowl||processor||pan,cover||drain||add||puree||press||chill||cut,0.0,0.0,0.0,0.0,0.0

In [ ]:
combined_df["Sub_region"].unique()

array(['Egyptian', 'Nigerian', 'Moroccan', 'Rest Middle Eastern',
       'Chinese', 'Thai', 'Indonesian', 'Bangladeshi', 'Vietnamese',
       'Israeli', 'Lebanese', 'Filipino', 'Indian', 'Korean', 'Malaysian',
       'Turkish', 'Japanese', 'Pakistani', 'Australian', 'Mexican',
       'Rest Caribbean', 'Puerto Rican', 'Jamaican', 'Cuban', 'Argentine',
       'Brazilian', 'Colombian', 'Chilean', 'Peruvian', 'Russian',
       'Danish', 'Scottish', 'English', 'UK', 'Welsh', 'Hungarian',
       'Swedish', 'Belgian', 'Norwegian', 'Austrian', 'Greek', 'French',
       'Swiss', 'Portuguese', 'Italian', 'Polish', 'Dutch', 'Irish',
       'German', 'Rest Eastern European', 'Spanish', 'Finnish', 'Czech',
       'US', 'Canadian', 'Somalian', 'Namibian', 'Angolan', 'Libyan',
       'Sudanese', 'Ethiopian', 'Laotian', 'Nepalese', 'Cambodian',
       'Palestinian', 'Saudi Arabian', 'Mongolian', 'Iraqi',
       'New Zealander', 'Honduran', 'Costa Rican', 'Guatemalan',
       'Ecuadorean', 'Venezuelan', 'Icelandic'], dtype=object)

In [ ]:
all_categories = pd.read_csv("/content/drive/MyDrive/Academic/COSY/Dataset/New_Unique_Ing_with_ID.csv")
all_categories.head()

,IngID,new_name,new_frequency,similarity_achieved,old_ing_id,old_ing_name,old_frequency,generic_name,wikilink,wikiimage,Doubt,10,FlavorDB_Category,Dietrx_Category,New_Category,Flavor_DB_Link,Diet_rx_link
0,0,salt,48195,1.0,1.0,salt,45409.0,Salt,https://en.wikipedia.org/wiki/Salt,https://upload.wikimedia.org/wikipedia/commons...,NaN,1.0,NaN,Additive-Salt,NaN,Salt~https://cosylab.iiitd.edu.in/flavordb/ent...,NaN
1,1,onion,35453,1.0,2.0,onion,32345.0,Onion,https://en.wikipedia.org/wiki/Onion,https://upload.wikimedia.org/wikipedia/commons...,NaN,32342.0,Vegetable-Bulb,Vegetable,NaN,Onion~https://cosylab.iiitd.edu.in/flavordb/en...,onion~https://cosylab.iiitd.edu.in/dietrx/get_...
2,2,butter,30038,1.0,4.0,butter,23765.0,Butter,https://en.wikipedia.org/wiki/Butter,https://upload.wikimedia.org/wikipedia/commons...,NaN,5.0,NaN,Dairy,NaN,Butter~https://cosylab.iiitd.edu.in/flavordb/e...,butter~https://cosylab.iiitd.edu.in/dietrx/get...
3,3,water,26790,1.0,5.0,water,23200.0,Water,https://en.wikipedia.org/wiki/Fresh_Water,https://upload.wikimedia.org/wikipedia/commons...,NaN,9.0,NaN,NaN,Incorrect Ingredient,Water~https://cosylab.iiitd.edu.in/flavordb/en...,NaN
4,4,garlic clove,25636,1.0,3.0,garlic clove,24780.0,Garlic,https://en.wikipedia.org/wiki/Garlic,https://upload.wikimedia.org/wikipedia/commons...,NaN,31.0,NaN,Herb,NaN,Garlic~https://cosylab.iiitd.edu.in/flavordb/e...,garlic~https://cosylab.iiitd.edu.in/dietrx/get...

In [ ]:
def find_recipe_avg_size(cuisine,diet_type=None):
  temp_df = combined_df[combined_df["Sub_region"]==cuisine]
  # if diet_type== "vegan":
  #   temp_df = temp_df[temp_df["vegan"]==1]
  # elif diet_type=="pescetarian":
  #   temp_df = temp_df[temp_df["pescetarian"]==1]
  # elif  diet_type== "ovo_lacto_vegetarian":
  #   temp_df = temp_df[temp_df["ovo_lacto_vegetarian"]==1]
  #   print(temp_df.shape)
  # elif diet_type== "ovo_vegetarian":
  #   temp_df = temp_df[temp_df["ovo_vegetarian"]==1]
  # elif diet_type== "lacto_vegetarian":
  #   temp_df = temp_df[temp_df["lacto_vegetarian"]==1]
  # #print(temp_df.shape)

  result = []
  for ind in temp_df.index:
    t = temp_df["ingredients"][ind]
    t = t.strip('][').split(', ')
    result.extend(t)
  # counter_result = Counter(result).most_common()
  # first_tuple_elements = [a_tuple[0] for a_tuple in counter_result]

  #Change: remove those ingredients which do not come in the category

  if diet_type== "vegan":
    # temp_df = temp_df[temp_df["vegan"]==1]for
    result_new=[] 
    for item in result:
      cat_list=all_categories[all_categories['generic_name']==item]['Dietrx_Category'].unique()
      if item != 'egg' and 'meat' not in cat_list and 'seafood' not in cat_list and 'dairy' not in cat_list:
        result_new.append(item)
  elif diet_type=="pescetarian":
    result_new=[] 
    for item in result:
      cat_list=all_categories[all_categories['generic_name']==item]['Dietrx_Category'].unique()
      if 'meat' not in cat_list:
        result_new.append(item)
    # temp_df = temp_df[temp_df["pescetarian"]==1]
  elif  diet_type== "ovo_lacto_vegetarian":
    result_new=[] 
    for item in result:
      cat_list=all_categories[all_categories['generic_name']==item]['Dietrx_Category'].unique()
      if 'meat' not in cat_list and 'seafood' not in cat_list:
        result_new.append(item)
    # temp_df = temp_df[temp_df["ovo_lacto_vegetarian"]==1]
  elif diet_type== "ovo_vegetarian":
    result_new=[] 
    for item in result:
      cat_list=all_categories[all_categories['generic_name']==item]['Dietrx_Category'].unique()
      if 'meat' not in cat_list and 'seafood' not in cat_list and 'dairy' not in cat_list:
        result_new.append(item)
    # temp_df = temp_df[temp_df["ovo_vegetarian"]==1]
  elif diet_type== "lacto_vegetarian":
    result_new=[] 
    for item in result:
      cat_list=all_categories[all_categories['generic_name']==item]['Dietrx_Category'].unique()
      if item != 'egg' and 'meat' not in cat_list and 'seafood' not in cat_list:
        result_new.append(item)
    # temp_df = temp_df[temp_df["lacto_vegetarian"]==1]

  counter_result = Counter(result).most_common()
  first_tuple_elements = [a_tuple[0] for a_tuple in counter_result]
  second_tuple_elements = [a_tuple[1]/len(counter_result) for a_tuple in counter_result]
  
  series=temp_df.groupby(['size']).count()/temp_df.shape[0]
  recipe_cdf = np.cumsum(series["Recipe_id"])
  random_size_number = random.random()
  recipe_cdf_list = recipe_cdf.to_list()
  i=0
  while(random_size_number>recipe_cdf_list[i]):
    i+=1
  recipe_avg_size=i+1  
  return recipe_avg_size, first_tuple_elements, second_tuple_elements

def choose_ingredients(cuisine, first_tuple_elements, second_tuple_elements, recipe_avg_size=10,diet_type=None):
  set_random_ingredient = set()
  if diet_type== "vegan":
    print("")

  elif diet_type=="pescetarian":
    pesc = all_categories[all_categories['Dietrx_Category'] == 'Seafood']
    pescetarian_set = set(pesc['generic_name'].unique())
    first_tuple_elements_new = []
    for ele in first_tuple_elements:
      if ele[0] == "'":
        ele = ele[1:-1]
        first_tuple_elements_new.append(ele)
    intersection_set = pescetarian_set.intersection(set(first_tuple_elements_new)) 
    choice_temp = random.choices(list(intersection_set))[0]
    set_random_ingredient.add(choice_temp)
  
  elif  diet_type == "ovo_lacto_vegetarian":
    ovo_lact = all_categories[all_categories['Dietrx_Category'] == 'Dairy']
    ovo_lacto_set = set(ovo_lact['generic_name'].unique())
    ovo_lacto_set.add('egg')
    first_tuple_elements_new = []
    for ele in first_tuple_elements:
      if ele[0] == "'":
        ele = ele[1:-1]
        first_tuple_elements_new.append(ele)
    intersection_set = ovo_lacto_set.intersection(set(first_tuple_elements_new)) 
    choice_temp = random.choices(list(intersection_set))[0]
    set_random_ingredient.add(choice_temp)
  
  elif diet_type== "ovo_vegetarian":
    set_random_ingredient.add("Egg")
  
  elif diet_type== "lacto_vegetarian":
    choice_temp=random.choices(lacto_set)[0]
    set_random_ingredient.add(choice_temp)

  while len(set_random_ingredient) < recipe_avg_size:
    choice_temp = random.choices(first_tuple_elements, weights=second_tuple_elements)[0]
    if choice_temp == 'nan':
      continue
    choice_temp = choice_temp[1:-1]
    set_random_ingredient.add(choice_temp)
  print(list(set_random_ingredient))
  return list(set_random_ingredient)

def choose_ingredients_by_cuisine(cuisine,diet_type=None):
  size, first, second = find_recipe_avg_size(cuisine,diet_type)
  print("size", size)
  return choose_ingredients(cuisine, first, second, size,diet_type)

In [ ]:
pescetarian_set = ["Shrimp", "Medium Shrimp", "Large Shrimp", "Oyster Sauce", "Scallion","Mussel", "Scallop", "Clam", "Crabmeat", "Tuna", "Anchovy Fillet","Salmon","Smoked Salmon"]
ovo_lacto_set= ["Milk","Butter","Egg","Cheddar Cheese"]
lacto_set= ["Milk","Butter","Cheddar Cheese"]

In [ ]:
small_db= pd.read_csv("/content/drive/MyDrive/Academic/COSY/Recipe_correct_ndb.csv")

In [ ]:
df_new=pd.read_json("/content/drive/MyDrive/Academic/COSY/Dataset/recipe_db_data.json","\t")

In [ ]:
df_new.head()

   Recipe_id                                              steps
0       2610   | 1.\tPlace 3 cups water, lentils, tomato, ca...
1       2611   | 1.\tHeat oil in a pot over medium heat; coo...
2       2612   | 1.\tHeat olive oil in a large saucepan over...
3       2613   | 1.\tCook the onions in 1 1/2 teaspoons of o...
4       2614   | 1.\tPreheat the oven to 350 degrees F (175 ...

In [ ]:
chosen_ingredients = choose_ingredients_by_cuisine("Indian", "ovo_lacto_vegetarian")

size 18
['salt pepper', 'chili pepper', 'potato', 'cashew', 'water', 'cumin', 'turmeric', 'coriander', 'garam masala', 'black mustard seed', 'lemongrass puree', 'egg', 'sugar', 'cumin seed', 'heavy cream', 'saffron', 'raisin', 'olive oil']

In [ ]:
# sub_region_cuisines = combined_df["Sub_region"].unique()
# cuisine_ingredient_dict={}
# for cuisine in sub_region_cuisines:
#   print(cuisine)
#   chosen_ingredients = choose_ingredients_by_cuisine(cuisine)
#   cuisine_ingredient_dict[cuisine]=chosen_ingredients
#   print()
# cuisine_ingredient_dict

#Generate recipes using the above generated ingredients

In [ ]:
!pip install transformers

Collecting transformers
  Downloading transformers-4.18.0-py3-none-any.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 28.5 MB/s
Collecting huggingface-hub<1.0,>=0.1.0
  Downloading huggingface_hub-0.5.1-py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 7.7 MB/s
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (1.21.5)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2019.12.20)
Collecting sacremoses
  Downloading sacremoses-0.0.49-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB 70.9 MB/s
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers) (3.6.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers) (4.64.0)
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Downloading tokenizers-0.12.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.6 MB)
     |████████████████████████████████| 6.6 MB 53.7 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers) (2.23.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers) (4.11.3)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 73.7 MB/s
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers) (21.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (4.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers) (3.0.8)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers) (3.8.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2021.10.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.1.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (7.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.15.0)
Installing collected packages: pyyaml, tokenizers, sacremoses, huggingface-hub, transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed huggingface-hub-0.5.1 pyyaml-6.0 sacremoses-0.0.49 tokenizers-0.12.1 transformers-4.18.0

In [ ]:
from tqdm import trange
import torch
import torch.nn.functional as F
import numpy as np
import re
import os
from transformers import AutoTokenizer,AutoModelWithLMHead
from transformers import GPT2LMHeadModel, GPT2Tokenizer

print(f"PyTorch version: {torch.__version__}")

# Model class to load the saved model, can use either of them
MODEL_CLASSES = {
    'gpt2': (GPT2LMHeadModel, GPT2Tokenizer),
}
MODEL_CLASSES1 = {
    'gpt2': (AutoModelWithLMHead, AutoTokenizer),
}


# seed values
def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)


def top_k_top_p_filtering(logits, top_k=0, top_p=0.0, filter_value=-float('Inf')):
    """ Filter a distribution of logits using top-k and/or nucleus (top-p) filtering
        Args:
            logits: logits distribution shape (vocabulary size)
            top_k > 0: keep only top k tokens with highest probability (top-k filtering).
            top_p > 0.0: keep the top tokens with cumulative probability >= top_p (nucleus filtering).
                Nucleus filtering is described in Holtzman et al. (http://arxiv.org/abs/1904.09751)
        From: https://gist.github.com/thomwolf/1a5a29f6962089e871b94cbd09daf317
    """
    assert logits.dim() == 1  # batch size 1 for now - could be updated for more but the code would be less clear
    top_k = min(top_k, logits.size(-1))  # Safety check
    if top_k > 0:
        # Remove all tokens with a probability less than the last token of the top-k
        indices_to_remove = logits < torch.topk(logits, top_k)[0][..., -1, None]
        logits[indices_to_remove] = filter_value

    if top_p > 0.0:
        sorted_logits, sorted_indices = torch.sort(logits, descending=True)
        cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)

        # Remove tokens with cumulative probability above the threshold
        sorted_indices_to_remove = cumulative_probs > top_p
        # Shift the indices to the right to keep also the first token above the threshold
        sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
        sorted_indices_to_remove[..., 0] = 0

        indices_to_remove = sorted_indices[sorted_indices_to_remove]
        logits[indices_to_remove] = filter_value
    return logits


def sample_sequence(model, length, context, tokenizer, num_samples=1, temperature=1, top_k=0, top_p=0.0, device = 'gpu'):
    end_token = tokenizer.convert_tokens_to_ids(["<END_RECIPE>"])[0]
    context = torch.tensor(context, dtype=torch.long, device=device)
    context = context.unsqueeze(0).repeat(num_samples, 1)
    generated = context
    with torch.no_grad():
        for _ in trange(length):
            inputs = {'input_ids': generated}
            outputs = model(**inputs)  # Note: we could also use 'past' with GPT-2/Transfo-XL/XLNet (cached hidden-states)
            next_token_logits = outputs[0][0, -1, :] / temperature
            filtered_logits = top_k_top_p_filtering(next_token_logits, top_k=top_k, top_p=top_p)
            next_token = torch.multinomial(F.softmax(filtered_logits, dim=-1), num_samples=1)
            generated = torch.cat((generated, next_token.unsqueeze(0)), dim=1)
            if next_token.item() == end_token:
                print('breaking----->>')
                break
    return generated

# global seed
set_seed(20)

# loadind the trained model

model_class, tokenizer_class = MODEL_CLASSES['gpt2']
tokenizer = tokenizer_class.from_pretrained('/content/drive/MyDrive/Final_Recipe_Gen_models/outputs/tempt/')
# tokenizer = tokenizer_class.from_pretrained('/content/drive/MyDrive/capstone-remoteserver/Final Work/outputs/tempt')
# model = model_class.from_pretrained('/content/drive/MyDrive/capstone-remoteserver/Final Work/outputs/tempt')
model = model_class.from_pretrained('/content/drive/MyDrive/Final_Recipe_Gen_models/outputs/tempt')
model.to(torch.device("cuda" ))
model.eval();

PyTorch version: 1.10.0+cu111

In [ ]:
# cuisine_ingredient_string_dict={}
# for cuisine in cuisine_ingredient_dict:
#   chosen_ingredients= cuisine_ingredient_dict[cuisine]
#   str_recipe=''
#   for item in chosen_ingredients:
#     str_recipe=str_recipe+item+','
#   str_recipe=str_recipe[:-1]
#   str_recipe+=';'
#   cuisine_ingredient_string_dict[cuisine]=str_recipe

In [ ]:
str_recipe=''
for item in chosen_ingredients:
  str_recipe=str_recipe+item+','
str_recipe=str_recipe[:-1]
str_recipe+=';'
# cuisine_ingredient_string_dict[cuisine]=str_recipe
cuisine_ingredient_string=str_recipe

In [ ]:
# cuisine_ingredient_string_dict

In [ ]:
# # taking input from the user for recipe
# # raw_text = input("Comma-separated ingredients, semicolon to close the list >>> ")
# for cuisine in cuisine_ingredient_string_dict:
#   raw_text= cuisine_ingredient_string_dict[cuisine]
#   # raw_text= str_recipe
#   prepared_input = '<RECIPE_START> <INPUT_START> ' + raw_text.replace(',', ' <NEXT_INPUT> ').replace(';', ' <INPUT_END>')
#   context_tokens = tokenizer.encode(prepared_input)
#   # 
#   out = sample_sequence(
#       model=model,
#       context=context_tokens,
#       tokenizer=tokenizer,
#       length=768,
#       temperature=1,
#       top_k=30,
#       top_p=1,
#       device=torch.device("cuda")
#   )
#   out = out[0, len(context_tokens):].tolist()
#   text = tokenizer.decode(out, clean_up_tokenization_spaces=True)
#   if "<RECIPE_END>" not in text:
#       print(text)
#       print("Failed to generate, recipe's too long")
# # salt, chicken, beef, milk, water, garlic, onion, vinegar;

In [ ]:

raw_text= cuisine_ingredient_string
# raw_text= str_recipe
prepared_input = '<RECIPE_START> <INPUT_START> ' + raw_text.replace(',', ' <NEXT_INPUT> ').replace(';', ' <INPUT_END>')
context_tokens = tokenizer.encode(prepared_input)
# 
out = sample_sequence(
    model=model,
    context=context_tokens,
    tokenizer=tokenizer,
    length=768,
    temperature=1,
    top_k=30,
    top_p=1,
    device=torch.device("cuda")
)
out = out[0, len(context_tokens):].tolist()
text = tokenizer.decode(out, clean_up_tokenization_spaces=True)
if "<RECIPE_END>" not in text:
    print(text)
    print("Failed to generate, recipe's too long")
# salt, chicken, beef, milk, water, garlic, onion, vinegar;

100%|██████████| 768/768 [00:34<00:00, 22.08it/s]

In [ ]:
# comparision to previous results
# formating and printing the generated recipe
user_input = prepared_input
user_input = user_input.replace('<RECIPE_START> <INPUT_START>', '## User inputs ##\n    - ').replace('<NEXT_INPUT>', '\n    -').replace('<INPUT_END>', '\n------------------------\n')
generated_recipe = str(text.replace('<TITLE_START>', '## Recipe Name:- ##\n').replace('<TITLE_END>', '\n')) \
                        .replace('<INGR_START>', '\n## Ingredients ##\n    -').replace('<NEXT_INGR>', '\n    -').replace('<INGR_END>', '\n\n') \
                        .replace('<INSTR_START>', '## Cooking instructions ##\n    -').replace('.','.\n    -').replace('<NEXT_INSTR>', '\n    -').replace('- <INSTR_END>', '\n\n') \
                        .replace(' <RECIPE_END>', '\n\n\n\nVoila Enjoy your recipe :)\n\n\n\n\n -----------\n')
                    

# print(user_input)
# print(generated_recipe)
end_ind=generated_recipe.find("---")
print(generated_recipe[:end_ind])

## Recipe Name:- ##
 Korma

## Ingredients ##
    - 1 tablespoon black mustard seeds
    - 1 tablespoon cumin seed
    - 1 teaspoon garam masala
    - 1 teaspoon turmeric
    - 1 teaspoon saffron, crushed
    - 1 teaspoon ground coriander
    - 2 tablespoons chili pepper
    - 500 g potatoes, cut into chunks
    - 2 stalks lemongrass, bruised and finely diced
    - 1 egg, whisked
    - 1 cup cashews, chopped
    - 1/2 cup raisins
    - 1 tablespoon lime juice or 1 tablespoon lemon juice
    - 1 tablespoon chopped fresh coriander
    - 1/2 teaspoon sugar
    - salt and pepper
    - 1 tablespoon water, as needed
    - 1 tablespoon olive oil

 ## Cooking instructions ##
    - Place the first 7 ingredients into a spice or coffee grinder and grind to a fine powder
    - Place potatoes in a saucepan of water and bring to the boil
    - Cook for about 6 to 8 minutes until tender
    - Place in a colander and run under cold water for a minute
    - While the potatoes are cooking, bring a large pot of salted water to a boil
    - Add cashew nuts and cook for 2 to 3 minutes or until tender
    - Drain and set aside
    - Drain well, then mash potatoes with lemon grass, egg, cashews, raisins, lime juice, coriander, sugar, salt and pepper
    - Place in a glass bowl, cover and chill until needed
    - Heat olive oil in a frying pan over low heat
    - Place korma into the pan, cover, and cook for 5 to 10 minutes, until just cooked through <INSTR_END>



Voila Enjoy your recipe :)

In [ ]:
start_point = text.find("<INGR_START>")
end_point = text.find("<INGR_END>")
next_ingr = "<NEXT_INGR>"
useful_text = text[start_point+12:end_point]

# for i in range(start_point, end_point):
  
#   print("hello")

ingredient_with_quantity = useful_text.split(next_ingr)
ingredient_with_quantity

[' 1 tablespoon black mustard seeds ',
 ' 1 tablespoon cumin seed ',
 ' 1 teaspoon garam masala ',
 ' 1 teaspoon turmeric ',
 ' 1 teaspoon saffron, crushed ',
 ' 1 teaspoon ground coriander ',
 ' 2 tablespoons chili pepper ',
 ' 500 g potatoes, cut into chunks ',
 ' 2 stalks lemongrass, bruised and finely diced ',
 ' 1 egg, whisked ',
 ' 1 cup cashews, chopped ',
 ' 1/2 cup raisins ',
 ' 1 tablespoon lime juice or 1 tablespoon lemon juice ',
 ' 1 tablespoon chopped fresh coriander ',
 ' 1/2 teaspoon sugar ',
 ' salt and pepper ',
 ' 1 tablespoon water, as needed ',
 ' 1 tablespoon olive oil ']

In [ ]:
parsed_ingredient_quantity=[]
for item in ingredient_with_quantity:
  # print(item.split())
  parsed_ingredient_quantity.append(item.split())
  # for i in range(len(item)):
  #   if 

parsed_ingredient_quantity

[['1', 'tablespoon', 'black', 'mustard', 'seeds'],
 ['1', 'tablespoon', 'cumin', 'seed'],
 ['1', 'teaspoon', 'garam', 'masala'],
 ['1', 'teaspoon', 'turmeric'],
 ['1', 'teaspoon', 'saffron,', 'crushed'],
 ['1', 'teaspoon', 'ground', 'coriander'],
 ['2', 'tablespoons', 'chili', 'pepper'],
 ['500', 'g', 'potatoes,', 'cut', 'into', 'chunks'],
 ['2', 'stalks', 'lemongrass,', 'bruised', 'and', 'finely', 'diced'],
 ['1', 'egg,', 'whisked'],
 ['1', 'cup', 'cashews,', 'chopped'],
 ['1/2', 'cup', 'raisins'],
 ['1',
  'tablespoon',
  'lime',
  'juice',
  'or',
  '1',
  'tablespoon',
  'lemon',
  'juice'],
 ['1', 'tablespoon', 'chopped', 'fresh', 'coriander'],
 ['1/2', 'teaspoon', 'sugar'],
 ['salt', 'and', 'pepper'],
 ['1', 'tablespoon', 'water,', 'as', 'needed'],
 ['1', 'tablespoon', 'olive', 'oil']]

In [ ]:
# Do 2 iterations, in 1st iteration convert fractions written in strings to decimals in string
# In next iteration, add the whole number with the decimal in strings

#First iteration, changed to decimal

def isfloat(num):
    try:
        float(num)
        return True
    except ValueError:
        return False
      
for j in range(len(parsed_ingredient_quantity)):
  ingredient_quantity=parsed_ingredient_quantity[j]
  for i in range(len(ingredient_quantity)):
    item=ingredient_quantity[i]
    if item.find("/")!=-1:
      before,after=item.split("/")
      decimal=str(float(before)/float(after))
      parsed_ingredient_quantity[j][i]=decimal

#Second iteration, adding to whole number
for i in range(len(parsed_ingredient_quantity)):
  ingredient_quantity=parsed_ingredient_quantity[i]
  # j=0
  # tot=
  # while float(ingredient_quantity[j]):
  #   ingredient_quantity[j]
  #   j+=1
  if isfloat(ingredient_quantity[1]):
    ans=str(float(ingredient_quantity[1])+float(ingredient_quantity[0]))
    new_ingredient_quantity = ingredient_quantity[2:]
  else:
    ans=ingredient_quantity[0]
    new_ingredient_quantity = ingredient_quantity[1:]
  new_ingredient_quantity.insert(0,ans)
  parsed_ingredient_quantity[i]=new_ingredient_quantity

In [ ]:
parsed_ingredient_quantity

[['1', 'tablespoon', 'black', 'mustard', 'seeds'],
 ['1', 'tablespoon', 'cumin', 'seed'],
 ['1', 'teaspoon', 'garam', 'masala'],
 ['1', 'teaspoon', 'turmeric'],
 ['1', 'teaspoon', 'saffron,', 'crushed'],
 ['1', 'teaspoon', 'ground', 'coriander'],
 ['2', 'tablespoons', 'chili', 'pepper'],
 ['500', 'g', 'potatoes,', 'cut', 'into', 'chunks'],
 ['2', 'stalks', 'lemongrass,', 'bruised', 'and', 'finely', 'diced'],
 ['1', 'egg,', 'whisked'],
 ['1', 'cup', 'cashews,', 'chopped'],
 ['0.5', 'cup', 'raisins'],
 ['1',
  'tablespoon',
  'lime',
  'juice',
  'or',
  '1',
  'tablespoon',
  'lemon',
  'juice'],
 ['1', 'tablespoon', 'chopped', 'fresh', 'coriander'],
 ['0.5', 'teaspoon', 'sugar'],
 ['salt', 'and', 'pepper'],
 ['1', 'tablespoon', 'water,', 'as', 'needed'],
 ['1', 'tablespoon', 'olive', 'oil']]

In [ ]:
# Assuming budget=500
# Total recipe cost=700
# Difference =>200/700
# Multiplying each value by 5/7

# fin_list=[]
for i in range(len(parsed_ingredient_quantity)):
  for j in range(len(parsed_ingredient_quantity[i])):
      if isfloat(parsed_ingredient_quantity[i][j]):
        parsed_ingredient_quantity[i][j]= round(float(parsed_ingredient_quantity[i][j])*(5/7),1)
# fin_list

In [ ]:
parsed_ingredient_quantity

[[0.7, 'tablespoon', 'black', 'mustard', 'seeds'],
 [0.7, 'tablespoon', 'cumin', 'seed'],
 [0.7, 'teaspoon', 'garam', 'masala'],
 [0.7, 'teaspoon', 'turmeric'],
 [0.7, 'teaspoon', 'saffron,', 'crushed'],
 [0.7, 'teaspoon', 'ground', 'coriander'],
 [1.4, 'tablespoons', 'chili', 'pepper'],
 [357.1, 'g', 'potatoes,', 'cut', 'into', 'chunks'],
 [1.4, 'stalks', 'lemongrass,', 'bruised', 'and', 'finely', 'diced'],
 [0.7, 'egg,', 'whisked'],
 [0.7, 'cup', 'cashews,', 'chopped'],
 [0.4, 'cup', 'raisins'],
 [0.7,
  'tablespoon',
  'lime',
  'juice',
  'or',
  0.7,
  'tablespoon',
  'lemon',
  'juice'],
 [0.7, 'tablespoon', 'chopped', 'fresh', 'coriander'],
 [0.4, 'teaspoon', 'sugar'],
 ['salt', 'and', 'pepper'],
 [0.7, 'tablespoon', 'water,', 'as', 'needed'],
 [0.7, 'tablespoon', 'olive', 'oil']]